[minecraft]
directory = "<minecraft server directory path>"
command = "java"
jar_file = "server.jar"
min_memory = "4G"
max_memory = "4G"
gui = false
stop_timeout = "30s"

[options]
log_level = "debug"
